# Generated by Django 2.2.5 on 2019-09-28 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190928_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='detail',
        ),
    ]
