# Generated by Django 2.2.5 on 2019-09-28 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_news_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
    ]
