# Generated by Django 2.2.5 on 2019-09-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190927_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time_lone',
            field=models.CharField(max_length=15),
        ),
    ]
