# Generated by Django 2.2.5 on 2019-09-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20190927_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time_lone',
            field=models.IntegerField(null=True),
        ),
    ]
